server:
  port: 8888
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: r1
          uri: http://localhost:8088
          predicates:
            - Path=/clients/**
        - id: r2
          uri: http://localhost:8088
          predicates:
            - Path=/client/**
        - id: r3
          uri: http://localhost:8089
          predicates:
            - Path=/voituress/**
        - id: r4
          uri: http://localhost:8089
          predicates:
            - Path=/voitures/**
  discovery:
    enabled: true
    locator:
      enabled: true
